version: "3.8"
services:
  ### Postgres Database ###
  postgres:
    container_name: db_postgres
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: amal
      POSTGRES_DB: tdd
    #networks:
    #  - mynet
  ### API Spring Boot ###
  api:
    container_name: TDD_dockerimage
    #image: TDD_dockerimage
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - postgres
    #links:
    #  - "postgres:postgres_db"
    environment:
      HOST_NAME: postgres
      PORT_NUM: 5432
      DATABASE_NAME: tdd
      PS_USERNAME: postgres
      PS_PW: amal
    #networks:
    #  - mynet

volumes:
  pgdata: {}
#networks:
#    mynet:
#      driver: bridge

#DATABASE_URL: postgresql://postgres:5432/db